[package]
name = "sky"
version = "0.1.0"
authors = ["Darwin D Wu <wuddarwin@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "0.2"
actix-web = "1.0.0-beta.2"
actix-files = "0.1.0-betsa.1"
env_logger = "0.6"
askama = "0.8"

[build-dependencies]
askama = "0.8"
