// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compute.proto

package compute

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Compute struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ComputeType          string   `protobuf:"bytes,2,opt,name=compute_type,json=computeType,proto3" json:"compute_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Compute) Reset()         { *m = Compute{} }
func (m *Compute) String() string { return proto.CompactTextString(m) }
func (*Compute) ProtoMessage()    {}
func (*Compute) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{0}
}

func (m *Compute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Compute.Unmarshal(m, b)
}
func (m *Compute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Compute.Marshal(b, m, deterministic)
}
func (m *Compute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Compute.Merge(m, src)
}
func (m *Compute) XXX_Size() int {
	return xxx_messageInfo_Compute.Size(m)
}
func (m *Compute) XXX_DiscardUnknown() {
	xxx_messageInfo_Compute.DiscardUnknown(m)
}

var xxx_messageInfo_Compute proto.InternalMessageInfo

func (m *Compute) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Compute) GetComputeType() string {
	if m != nil {
		return m.ComputeType
	}
	return ""
}

type ComputeListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeListRequest) Reset()         { *m = ComputeListRequest{} }
func (m *ComputeListRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeListRequest) ProtoMessage()    {}
func (*ComputeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{1}
}

func (m *ComputeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeListRequest.Unmarshal(m, b)
}
func (m *ComputeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeListRequest.Marshal(b, m, deterministic)
}
func (m *ComputeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeListRequest.Merge(m, src)
}
func (m *ComputeListRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeListRequest.Size(m)
}
func (m *ComputeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeListRequest proto.InternalMessageInfo

type ComputeListResponse struct {
	Computes             []*Compute `protobuf:"bytes,1,rep,name=computes,proto3" json:"computes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ComputeListResponse) Reset()         { *m = ComputeListResponse{} }
func (m *ComputeListResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeListResponse) ProtoMessage()    {}
func (*ComputeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{2}
}

func (m *ComputeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeListResponse.Unmarshal(m, b)
}
func (m *ComputeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeListResponse.Marshal(b, m, deterministic)
}
func (m *ComputeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeListResponse.Merge(m, src)
}
func (m *ComputeListResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeListResponse.Size(m)
}
func (m *ComputeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeListResponse proto.InternalMessageInfo

func (m *ComputeListResponse) GetComputes() []*Compute {
	if m != nil {
		return m.Computes
	}
	return nil
}

func init() {
	proto.RegisterType((*Compute)(nil), "compute.Compute")
	proto.RegisterType((*ComputeListRequest)(nil), "compute.ComputeListRequest")
	proto.RegisterType((*ComputeListResponse)(nil), "compute.ComputeListResponse")
}

func init() { proto.RegisterFile("compute.proto", fileDescriptor_7a04c0385a1d134f) }

var fileDescriptor_7a04c0385a1d134f = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2d,
	0x28, 0x2d, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x6c, 0xb8,
	0xd8, 0x9d, 0x21, 0x4c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0xa6, 0xcc, 0x14, 0x21, 0x45, 0x2e, 0x1e, 0xa8, 0xaa, 0xf8, 0x92, 0xca, 0x82, 0x54, 0x09,
	0x26, 0xb0, 0x0c, 0x37, 0x54, 0x2c, 0xa4, 0xb2, 0x20, 0x55, 0x49, 0x84, 0x4b, 0x08, 0xaa, 0xdb,
	0x27, 0xb3, 0xb8, 0x24, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0xc9, 0x99, 0x4b, 0x18, 0x45,
	0xb4, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x87, 0x8b, 0x03, 0xaa, 0xb7, 0x58, 0x82, 0x51,
	0x81, 0x59, 0x83, 0xdb, 0x48, 0x40, 0x0f, 0xe6, 0x2a, 0xa8, 0xfa, 0x20, 0xb8, 0x0a, 0xa3, 0x60,
	0x2e, 0x3e, 0xa8, 0x60, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x23, 0x17, 0x0b, 0xc8,
	0x3c, 0x21, 0x69, 0x74, 0x5d, 0x48, 0x76, 0x4b, 0xc9, 0x60, 0x97, 0x84, 0x38, 0x21, 0x89, 0x0d,
	0xec, 0x7b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x94, 0x3b, 0x70, 0x0e, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ComputeServiceClient is the client API for ComputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ComputeServiceClient interface {
	List(ctx context.Context, in *ComputeListRequest, opts ...grpc.CallOption) (*ComputeListResponse, error)
}

type computeServiceClient struct {
	cc *grpc.ClientConn
}

func NewComputeServiceClient(cc *grpc.ClientConn) ComputeServiceClient {
	return &computeServiceClient{cc}
}

func (c *computeServiceClient) List(ctx context.Context, in *ComputeListRequest, opts ...grpc.CallOption) (*ComputeListResponse, error) {
	out := new(ComputeListResponse)
	err := c.cc.Invoke(ctx, "/compute.ComputeService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeServiceServer is the server API for ComputeService service.
type ComputeServiceServer interface {
	List(context.Context, *ComputeListRequest) (*ComputeListResponse, error)
}

func RegisterComputeServiceServer(s *grpc.Server, srv ComputeServiceServer) {
	s.RegisterService(&_ComputeService_serviceDesc, srv)
}

func _ComputeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compute.ComputeService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).List(ctx, req.(*ComputeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ComputeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compute.ComputeService",
	HandlerType: (*ComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ComputeService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compute.proto",
}
